"""empty message

Revision ID: 54aad68d69af
Revises: b57cd36de14d
Create Date: 2022-05-31 17:14:36.430510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aad68d69af'
down_revision = 'b57cd36de14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genre')
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    op.add_column('Artist', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
